import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { copyFile, cp, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";
import {
  HANDOFF_SNAPSHOT_END,
  HANDOFF_SNAPSHOT_START,
  loadProject,
  MANAGED_END,
  MANAGED_START,
  readPublicSchema,
  refreshHandoff,
  syncProject,
  validateProject,
} from "../dist/index.js";
import { createTemporaryDirectory, removeTemporaryDirectory } from "./helpers.mjs";

const execFileAsync = promisify(execFile);

test("Carrylog upgrades a beta.3 repository without moving or duplicating persisted state", async () => {
  const root = await createTemporaryDirectory("carrylog-beta3-upgrade-");
  try {
    await materializeBeta3Repository(root);
    const configPath = path.join(root, ".agent-context", "config.yaml");
    const schemaPath = path.join(root, ".agent-context", "config.schema.json");
    const handoffPath = path.join(root, ".agent-context", "handoff.md");
    const instructionsPath = path.join(root, ".agent-context", "instructions.md");
    const configBefore = await readFile(configPath, "utf8");
    const schemaBefore = await readFile(schemaPath, "utf8");

    const handoff = await readFile(handoffPath, "utf8");
    const firstLineEnd = handoff.indexOf("\n") + 1;
    await writeFile(
      handoffPath,
      `${handoff.slice(0, firstLineEnd)}\n${HANDOFF_SNAPSHOT_START}\n## Repository evidence\n\nLegacy beta.3 snapshot.\n${HANDOFF_SNAPSHOT_END}\n${handoff.slice(firstLineEnd)}`,
      "utf8",
    );

    await git(root, ["init", "-b", "main"]);
    await git(root, ["config", "user.email", "carrylog-tests@example.invalid"]);
    await git(root, ["config", "user.name", "Carrylog Tests"]);
    await git(root, ["add", "."]);
    await git(root, ["commit", "-m", "Legacy beta3 fixture"]);

    let project = await loadProject(root);
    const before = await validateProject(project);
    const beforeCodes = before.diagnostics.map((diagnostic) => diagnostic.code);
    assert.equal(beforeCodes.includes("E_ADAPTER_DRIFT"), true);
    assert.equal(beforeCodes.includes("E_LEGACY_CLI_INSTRUCTION"), true);
    assert.equal(beforeCodes.includes("E_UNMANAGED_ADAPTER"), false);
    assert.equal(beforeCodes.includes("E_MANAGED_MARKERS"), false);

    const synchronized = await syncProject(project, {
      adopt: false,
      check: false,
      dryRun: false,
    });
    assert.equal(synchronized.wrote, true);
    project = await loadProject(root);
    assert.equal((await validateProject(project)).valid, true);
    const migratedInstructions = await readFile(instructionsPath, "utf8");
    const publishedInstructions = await readFile(
      path.resolve("tests", "fixtures", "beta3", "context", "instructions.md"),
      "utf8",
    );
    assert.equal(
      migratedInstructions,
      publishedInstructions.replace("`ackit validate`", "`carrylog validate`"),
    );
    assert.doesNotMatch(migratedInstructions, /\backit\b/);

    for (const output of ["AGENTS.md", "CLAUDE.md"]) {
      const content = await readFile(path.join(root, output), "utf8");
      assert.match(content, /^# Team-owned instructions\n/);
      assert.match(content, /This section is generated by Carrylog\./);
      assert.match(content, /Run `carrylog sync`/);
      assert.equal(count(content, MANAGED_START), 1);
      assert.equal(count(content, MANAGED_END), 1);
    }

    const refreshed = await refreshHandoff(project, { check: false, dryRun: false });
    assert.equal(refreshed.wrote, true);
    const refreshedHandoff = await readFile(handoffPath, "utf8");
    assert.equal(count(refreshedHandoff, HANDOFF_SNAPSHOT_START), 1);
    assert.equal(count(refreshedHandoff, HANDOFF_SNAPSHOT_END), 1);

    const repeatedSync = await syncProject(await loadProject(root), {
      adopt: false,
      check: true,
      dryRun: false,
    });
    assert.equal(repeatedSync.drift, false);
    const repeatedHandoff = await refreshHandoff(await loadProject(root), {
      check: true,
      dryRun: false,
    });
    assert.equal(repeatedHandoff.drift, false);

    assert.equal(await readFile(configPath, "utf8"), configBefore);
    assert.equal(await readFile(schemaPath, "utf8"), schemaBefore);
    assert.equal(schemaBefore, readPublicSchema());
    await assert.rejects(() => stat(path.join(root, ".carrylog")), { code: "ENOENT" });
  } finally {
    await removeTemporaryDirectory(root);
  }
});

test("Carrylog refuses to rewrite customized beta.3 instructions and reports a manual migration", async () => {
  const root = await createTemporaryDirectory("carrylog-beta3-customized-");
  try {
    await materializeBeta3Repository(root);
    const instructionsPath = path.join(root, ".agent-context", "instructions.md");
    const adapterPath = path.join(root, "AGENTS.md");
    const customized = `${await readFile(instructionsPath, "utf8")}\n- Keep this team-authored rule.\n`;
    await writeFile(instructionsPath, customized, "utf8");
    const adapterBefore = await readFile(adapterPath, "utf8");

    const project = await loadProject(root);
    const validation = await validateProject(project);
    assert.equal(validation.valid, false);
    assert.equal(
      validation.diagnostics.some((diagnostic) => diagnostic.code === "E_LEGACY_CLI_INSTRUCTION"),
      true,
    );
    await assert.rejects(
      () => syncProject(project, { adopt: false, check: false, dryRun: false }),
      (error) =>
        error.code === "E_CONTEXT_INVALID" &&
        error.diagnostics.some((diagnostic) => diagnostic.code === "E_LEGACY_CLI_INSTRUCTION"),
    );
    assert.equal(await readFile(instructionsPath, "utf8"), customized);
    assert.equal(await readFile(adapterPath, "utf8"), adapterBefore);

    await writeFile(
      instructionsPath,
      customized.replace("`ackit validate`", "`carrylog validate`"),
      "utf8",
    );
    const repaired = await syncProject(await loadProject(root), {
      adopt: false,
      check: false,
      dryRun: false,
    });
    assert.equal(repaired.wrote, true);
    assert.match(await readFile(instructionsPath, "utf8"), /Keep this team-authored rule/);
    assert.equal((await validateProject(await loadProject(root))).valid, true);
  } finally {
    await removeTemporaryDirectory(root);
  }
});

test("Carrylog migrates an untouched CRLF beta.3 instruction template without newline drift", async () => {
  const root = await createTemporaryDirectory("carrylog-beta3-crlf-");
  try {
    await materializeBeta3Repository(root);
    const instructionsPath = path.join(root, ".agent-context", "instructions.md");
    const legacy = await readFile(instructionsPath, "utf8");
    await writeFile(instructionsPath, legacy.replaceAll("\n", "\r\n"), "utf8");

    await syncProject(await loadProject(root), { adopt: false, check: false, dryRun: false });
    const migrated = await readFile(instructionsPath, "utf8");
    assert.equal(
      migrated,
      legacy.replace("`ackit validate`", "`carrylog validate`").replaceAll("\n", "\r\n"),
    );
    assert.equal(migrated.replaceAll("\r\n", "").includes("\n"), false);
  } finally {
    await removeTemporaryDirectory(root);
  }
});

test("Carrylog migration follows configured paths instead of a mutable document ID", async () => {
  const root = await createTemporaryDirectory("carrylog-beta3-renamed-id-");
  try {
    await materializeBeta3Repository(root);
    const configPath = path.join(root, ".agent-context", "config.yaml");
    const config = await readFile(configPath, "utf8");
    await writeFile(configPath, config.replace("id: instructions", "id: rules"), "utf8");

    const synchronized = await syncProject(await loadProject(root), {
      adopt: false,
      check: false,
      dryRun: false,
    });
    assert.equal(synchronized.wrote, true);
    const instructions = await readFile(
      path.join(root, ".agent-context", "instructions.md"),
      "utf8",
    );
    assert.match(instructions, /Run `carrylog validate`/);
    assert.equal((await validateProject(await loadProject(root))).valid, true);
  } finally {
    await removeTemporaryDirectory(root);
  }
});

test("Carrylog reports stock beta.3 migration in check mode without changing canonical prose", async () => {
  const root = await createTemporaryDirectory("carrylog-beta3-check-");
  try {
    await materializeBeta3Repository(root);
    const instructionsPath = path.join(root, ".agent-context", "instructions.md");
    const legacy = await readFile(instructionsPath, "utf8");

    const checked = await syncProject(await loadProject(root), {
      adopt: false,
      check: true,
      dryRun: false,
    });
    assert.equal(checked.wrote, false);
    assert.equal(checked.drift, true);
    assert.equal(
      checked.changes.some(
        (change) => change.path === ".agent-context/instructions.md" && change.kind === "update",
      ),
      true,
    );
    assert.equal(await readFile(instructionsPath, "utf8"), legacy);
    assert.equal((await validateProject(await loadProject(root))).valid, false);
  } finally {
    await removeTemporaryDirectory(root);
  }
});

async function materializeBeta3Repository(root) {
  await cp(
    path.resolve("tests", "fixtures", "beta3", "context"),
    path.join(root, ".agent-context"),
    { recursive: true },
  );
  await copyFile(
    path.resolve("schemas", "config-v1.schema.json"),
    path.join(root, ".agent-context", "config.schema.json"),
  );

  for (const [output, fixture] of [
    ["AGENTS.md", "codex.md"],
    ["CLAUDE.md", "claude.md"],
  ]) {
    const legacyBody = await readFile(
      path.resolve("tests", "fixtures", "beta3", "adapters", fixture),
      "utf8",
    );
    await writeFile(
      path.join(root, output),
      `# Team-owned instructions\n\n${MANAGED_START}\n${legacyBody.trim()}\n${MANAGED_END}\n`,
      "utf8",
    );
  }
}

async function git(root, arguments_) {
  await execFileAsync("git", arguments_, {
    cwd: root,
    env: { ...process.env, GIT_OPTIONAL_LOCKS: "0", LC_ALL: "C" },
  });
}

function count(content, value) {
  return content.split(value).length - 1;
}
