import path from "node:path";
import type { AdapterConfig, ProjectConfig } from "../domain/types.js";
import { CLI_NAME, PRODUCT_NAME } from "../product.js";
import { getAdapterDefinition } from "./registry.js";

export function renderAdapter(config: ProjectConfig, adapter: AdapterConfig): string {
  const always = config.documents.filter((document) => document.load === "always");
  const onDemand = config.documents.filter((document) => document.load === "on-demand");
  const lines = [
    `# ${getAdapterDefinition(adapter.type).label} project context`,
    "",
    `This section is generated by ${PRODUCT_NAME}. The canonical project memory lives in \`.agent-context/\`.`,
    "",
    "Before doing project work, read these files in order:",
    "",
    ...always.map(
      (document, index) =>
        `${index + 1}. ${markdownCodeSpan(contextDocumentPath(document.path))} — ${document.description}`,
    ),
  ];

  if (onDemand.length > 0) {
    lines.push("", "Load these references only when the task needs them:", "");
    for (const document of onDemand) {
      const triggers = document.triggers?.length
        ? ` Triggers: ${document.triggers.join(", ")}.`
        : "";
      lines.push(
        `- ${markdownCodeSpan(contextDocumentPath(document.path))} — ${document.description}.${triggers}`,
      );
    }
  }

  lines.push(
    "",
    "Follow the update and handoff rules in the loaded context. If code and context disagree, report the mismatch before making a consequential change.",
    "",
    `Do not edit this managed section directly. Run \`${CLI_NAME} sync\` after changing \`.agent-context/config.yaml\`.`,
  );
  return lines.join("\n");
}

function contextDocumentPath(documentPath: string): string {
  return path.posix.join(".agent-context", documentPath);
}

export function markdownCodeSpan(value: string): string {
  const longestRun = Math.max(0, ...[...value.matchAll(/`+/g)].map((match) => match[0].length));
  const delimiter = "`".repeat(longestRun + 1);
  const padding = value.startsWith("`") || value.endsWith("`") ? " " : "";
  return `${delimiter}${padding}${value}${padding}${delimiter}`;
}
