import path from "node:path";
import type { AdapterConfig, ProjectConfig } from "../domain/types.js";

const ADAPTER_LABELS: Record<AdapterConfig["type"], string> = {
  codex: "Codex",
  claude: "Claude Code",
};

export function renderAdapter(config: ProjectConfig, adapter: AdapterConfig): string {
  const always = config.documents.filter((document) => document.load === "always");
  const onDemand = config.documents.filter((document) => document.load === "on-demand");
  const lines = [
    `# ${ADAPTER_LABELS[adapter.type]} project context`,
    "",
    "This section is generated by Agent Context Kit. The canonical project memory lives in `.agent-context/`.",
    "",
    "Before doing project work, read these files in order:",
    "",
    ...always.map(
      (document, index) =>
        `${index + 1}. \`${contextDocumentPath(document.path)}\` — ${document.description}`,
    ),
  ];

  if (onDemand.length > 0) {
    lines.push("", "Load these references only when the task needs them:", "");
    for (const document of onDemand) {
      const triggers = document.triggers?.length
        ? ` Triggers: ${document.triggers.join(", ")}.`
        : "";
      lines.push(
        `- \`${contextDocumentPath(document.path)}\` — ${document.description}.${triggers}`,
      );
    }
  }

  lines.push(
    "",
    "Follow the update and handoff rules in the loaded context. If code and context disagree, report the mismatch before making a consequential change.",
    "",
    "Do not edit this managed section directly. Run `ackit sync` after changing `.agent-context/config.yaml`.",
  );
  return lines.join("\n");
}

function contextDocumentPath(documentPath: string): string {
  return path.posix.join(".agent-context", documentPath);
}
